[phases.setup]
cmds = [
    "mkdir -p /app/.php-custom-config", # Create directory for custom PHP configuration
    "cp coolify-php.ini /app/.php-custom-config/"  # Copy custom PHP configuration file
]

[phases.build]
cmds = [
    "php artisan migrate --seed", # Run Laravel migrations
    "php artisan storage:link", # Create symbolic link for storage
    "chmod -R 777 vendor/mpdf/mpdf/tmp", # Ensure proper permissions for the mpdf tmp directory
    "apt install -y sed"  # Install sed for modifying configuration files
]

[phases.start]
cmds = [
    "export PHP_INI_SCAN_DIR=/app/.php-custom-config", # Set PHP environment variable for runtime
    "pkill -f 'php artisan schedule:work' || true", # Stop any running schedule:work processes
    "nohup php artisan schedule:work > /dev/null 2>&1 &"  # Start Laravel scheduler in the background
]
