[phases.setup]
cmds = [
    "mkdir -p /app/.php-custom-config",                        # PHP custom config dir
    "cp coolify-php.ini /app/.php-custom-config/"             # Copy PHP config
]

[phases.build]
cmds = [
    "npm install",                                            # Install frontend deps
    "npm run build",                                          # Build frontend (Vite)
    "php artisan config:cache",                              # Cache config
    "php artisan storage:link",                              # Create symlink for storage
    "php artisan migrate --force",                           # Run migrations safely
    "chmod -R 777 vendor/mpdf/mpdf/tmp",                     # mpdf tmp permission
    "apt install -y sed"                                     # Optional: sed install
]

[phases.start]
cmds = [
    "export PHP_INI_SCAN_DIR=/app/.php-custom-config",        # Load custom PHP config
    "pkill -f 'php artisan schedule:work' || true",           # Kill old scheduler
    "nohup php artisan schedule:work > /dev/null 2>&1 &"      # Start scheduler
]
