[phases.setup]
cmds = [
    "mkdir -p /app/.php-custom-config",
    "cp coolify-php.ini /app/.php-custom-config/"
]

[phases.build]
cmds = [
    "npm install",
    "npm run build",
    "php artisan config:cache",
    "php artisan storage:link",
    "php artisan migrate --force",
    "chmod -R 777 vendor/mpdf/mpdf/tmp",
    "apt install -y sed"
]

[phases.start]
cmds = [
    "export PHP_INI_SCAN_DIR=/app/.php-custom-config",
    "pkill -f 'php artisan schedule:work' || true",
    "nohup php artisan schedule:work > /dev/null 2>&1 &",
    "if [ -f ../nginx.conf ]; then sed -i '/http {/a\\client_max_body_size 2G;' ../nginx.conf && sed -i '/server {/a\\client_max_body_size 2G;' ../nginx.conf && nginx -s reload; else echo 'nginx.conf not found'; fi"
]
